# This file is a template, and might need editing before it works on your project.
image: python:2.7.14

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - python -m unittest -v tests
